### PR TITLE
feat: commit conventions

### PR DESCRIPTION
**Pull request by Berkmann18**
Follow up of https://github.com/all-contributors/all-contributors-cli/pull/159 but for the bot.

### CODE REVIEW

**Comment by jakebolam** [comment]
This looks great. Almost there @Berkmann18 !

**Comment by jsoref** [comment]
@jakebolam do you happen to remember what the difference between `almost there` and `ready` was?

I understand this PR is stale (conflicts)... But without a hint about what's missing, it seems hard for anyone to pick up.

**Comment by gr2m** [comment]
I think this PR can be closed. I would not enforce commit conventions on contributors, we can fix the commit messages using `squash & merge` when merging PRs. I'd suggest we close the PR @Berkmann18

**Comment by Berkmann18** [comment]
> I think this PR can be closed. I would not enforce commit conventions on contributors, we can fix the commit messages using squash & merge when merging PRs. I'd suggest we close the PR @Berkmann18

For this org sure, but for others where the commit convention isn't the same, it makes it an unnecessary annoyance.

**Comment by gr2m** [comment]
sorry, nevermind my comment, I misunderstood the PR. I thought it was about enforcing commit messages in this repository, not supporting multiple commit conventions by the app.

**Comment by Berkmann18** [comment]
Ah ok, no worries, it was indeed aimed at other repos where the app is used.

**Pull request closed without merging**
