### PR TITLE
feat(processIssueComment): add research contribution type

### PR DESCRIPTION
**Pull request by LaChapeliere**
Add a research contribution type with variant mappings, for people doing literature review, code
prototyping or any other research-related activity.

Part 3/3 of #446

Why:
For open science projects or dev projects with a research component, people carrying out research tasks cannot always be acknowledged with the existing types.

Adding the type and variants to the bot.

Checklist:

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged
- [ ] Added myself to contributors table

I honestly have no idea how to test that the addition is working properly.

Closes https://github.com/all-contributors/all-contributors/issues/446

### CODE REVIEW

**Comment by Berkmann18** [comment]
@LaChapeliere Could you bump the CLI version to the latest one (v6.19, that include your changes)?

**Comment by LaChapeliere** [comment]
> @LaChapeliere Could you bump the CLI version to the latest one (v6.19, that include your changes)?

Only in package.json, right?

**Comment by Berkmann18** [comment]
> Only in package.json, right?

Yeah, that should also update _yarn.lock_ using `yarn`.

**Comment by LaChapeliere** [comment]
> > Only in package.json, right?
> 
> Yeah, that should also update _yarn.lock_ using `yarn`.

Thanks, should be all good now.

**Review by Berkmann18 — APPROVED** [review]

**Comment by Berkmann18** [comment]
@all-contributors Please add @LaChapeliere for code.

**Comment by gr2m** [comment]
this will be fixed via #330

**Pull request closed without merging**
