### PR TITLE
feat(contribution-types): adds mentoring

### PR DESCRIPTION
**Pull request by mloning**
**What**:
Add support for mentoring (see https://github.com/all-contributors/all-contributors/issues/423)

**Why**:

**How**:
Added mentoring to [`src/tasks/processIssueComment/utils/parse-comment/index.js`](https://github.com/all-contributors/all-contributors-bot/blob/master/src/tasks/processIssueComment/utils/parse-comment/index.js)

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table 

**Comments**:
If tests are needed, could you point me to the files that I have to change/add?

### CODE REVIEW

**Comment by mloning** [comment]
Seems like the `test_and_deploy` check got stuck? Is there anything else I need to do?

**Review by Berkmann18 — APPROVED** [review]

**Comment by omarcostahamido** [comment]
bump

**Comment by Berkmann18** [comment]
Hopefully, the required check will stop hanging.

**Comment by omarcostahamido** [comment]
bump

(sorry for doing it again, but it has been a while...)

I'll do another PR if it's necessary (#320 ), just let me(us) know what we can do to get this merged.

Thanks!

**Comment by Berkmann18** [comment]
@jakebolam Any ideas as to why this CI issue happens?

**Comment by omarcostahamido** [comment]
_eeek_
why is it so hard to fix this?

**Comment by omarcostahamido** [comment]
ok, now it is giving some more insightful information: conflicting files.
>src/tasks/processIssueComment/utils/parse-comment/index.js
>yarn.lock

@mloning can you fix the PR branch?
@Berkmann18 as soon as he does that, can you merge it?

thx

**Comment by mloning** [comment]
@omarcostahamido thanks for looking into this. Not sure what I have to do, git tells me the files I changed were deleted on master? Have they been moved?

**Comment by Berkmann18** [comment]
The whole project had an overhaul, and the file where you changes would essentially move to is: https://github.com/all-contributors/app/blob/master/lib/parse-comment.js
@mloning So if you port your changes to that file (after rebasing), the PR should be mergeable. Apologies for the delay.

I was hoping to have documentation around the new architecture that will affect the other repos but life got on the way.

**Comment by mloning** [comment]
@omarcostahamido @Berkmann18 alright I cleaned it up - anything else still missing or is this good to go?

**Review by Berkmann18 — APPROVED** [review]
Awesome! Thanks a lot!

**Comment by Berkmann18** [comment]
@gr2m I see that Vercel is having an auth problem, is there anything we can do to fix that?
If not I'll merge it.

**Comment by gr2m** [comment]
> @gr2m I see that Vercel is having an auth problem, is there anything we can do to fix that?
> If not I'll merge it.

I had to authorize the deploy because the PR is from a fork. I should be able to invite to the Vercel org, but it's $20/month, that I'm currently paying. Okay if I do the approvals for now, until we either get sponsoring from Vercel, or move to begin.com for deployments (which is something I'd like to do anyway)

**Comment by gr2m** [comment]
You can install https://github.com/apps/all-contributors-preview for testing the change. Make sure you don't have https://github.com/apps/allcontributors installed on the same repository, the two might conflict with each other

**Review by gr2m — APPROVED** [review]
looks good to me:
https://github.com/gr2m/sandbox/issues/163#issuecomment-760435670

**Comment by omarcostahamido** [comment]
omg, we did it, at last!
thank you @mloning @Berkmann18 @gr2m 
🎉

**Pull request merged**
