### PR TITLE
feat: commit conventions

### PR DESCRIPTION
**Pull request by Berkmann18**
Updated version of #200

### CODE REVIEW

**Comment by gr2m** [comment]
@Berkmann18 if you want to test the deployment for this PR, you can update the webhook URL to `https://app-git-commit-conv.all-contributors-app.vercel.app/api/github/webhooks` at https://github.com/organizations/all-contributors/settings/apps/all-contributors-preview#integration_hook_attributes_active

**Comment by Berkmann18** [comment]
The link 404s for me :/.

**Comment by gr2m** [comment]
try again please

**Review by Ely68 — CHANGES_REQUESTED** [review]
exports[`issue_comment event skipCi=false: request body 5`] = `
Object {
  "body": "@jakebolam 
I've put up [a pull request](https://github.com/all-contributors/all-contributors-bot/pull/1347) to add @jakebolam! :tada:",
}
`;

**Comment by Ely68** [comment]
#228

**Review by Ely68 — COMMENTED** [review]
test/integration/__snapshots__/issue_comment.test.js.snap

**Review by Ely68 — APPROVED** [review]

**Review by Ely68 — APPROVED** [review]

**Review by Ely68 — COMMENTED** [review]
commit convention

**Comment by Berkmann18** [comment]
@gr2m Not since I last worked on this which wasn't a high priority thing.

**Review by tenshiAMD — CHANGES_REQUESTED** [review]
@Berkmann18 Hi, please rebase to `master` branch first so we can proceed with this PR. Thanks!

**Comment by tenshiAMD** [comment]
> @gr2m Not since I last worked on this which wasn't a high priority thing.

@Berkmann18 Can I help check this one?

**Comment by Berkmann18** [comment]
@tenshiAMD I've resolved the conflict. And yeah, you can help check that.

**Review by tenshiAMD — APPROVED** [review]

**Comment by tenshiAMD** [comment]
> @Berkmann18 if you want to test the deployment for this PR, you can update the webhook URL to `https://app-git-commit-conv.all-contributors-app.vercel.app/api/github/webhooks` at [github.com/organizations/all-contributors/settings/apps/all-contributors-preview#integration_hook_attributes_active](https://github.com/organizations/all-contributors/settings/apps/all-contributors-preview#integration_hook_attributes_active)

@gr2m @Berkmann18 all looks good now. how can we test live?

**Review by tenshiAMD — CHANGES_REQUESTED** [review]
@Berkmann18 @gr2m almost forgot, we need to update the documentation regarding this one.

oh, it's already included here (https://github.com/all-contributors/all-contributors/blob/2fdeea1fbe1788e223d8f34923ab38ec6ab33934/docs/cli/configuration.md#L24)

**Comment by tenshiAMD** [comment]
@Berkmann18 @gr2m I think we should set the default to use `angular` since that's the currently being used now

**Review by tenshiAMD — APPROVED** [review]

**Comment by tenshiAMD** [comment]
Resolves https://github.com/all-contributors/app/issues/132

**Comment by Berkmann18** [comment]
> @Berkmann18 @gr2m I think we should set the default to use `angular` since that's the currently being used right now

Not every repo use a commit convention and the setting was the users not just us.

**Comment by tenshiAMD** [comment]
> Not every repo use a commit convention and the setting was the users not just us.

@Berkmann18 yes that's true however in the app the default is using `angular`. is CLI currently using` none`?

**Comment by Berkmann18** [comment]
They both should have been the same, it must have been a mistake or a leftover from some corrections.

**Pull request merged**
