### PR TITLE
feat: improve the title and body of the pull request

### PR DESCRIPTION
**Pull request by ouuan**
1.  Add contribution types in the title.
2.  Remove the "s" in "Adds" in the body. An alternative is "This PR adds", but IMO "Adds" doesn't make sense.

### CODE REVIEW

**Review by gr2m — CHANGES_REQUESTED** [review]
Can you update the tests to make them pass again after your change?

**Review by gr2m — APPROVED** [review]
Thanks!

**Comment by gr2m** [comment]
@all-contributors please add @ouuan for code

**Comment by Jesusizalive96** [comment]
https://github.com/all-contributors/app/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by Jesusizalive96** [comment]
> 1.  Add contribution types in the title.
> 2.  Remove the "s" in "Adds" in the body. An alternative is "This PR adds", but IMO "Adds" doesn't make sense.

https://github.com/all-contributors/app/pull/361

**Pull request merged**
